apiVersion: v1
kind: Pod
metadata:
  name: jupyter-pod
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: nautilus.io/sdsuinstruction
              operator: Exists
  tolerations:
  - effect: NoSchedule
    key: nautilus.io/sdsu-fix
    operator: Exists
  containers:
  - name: jupyter
    image: gitlab-registry.nrp-nautilus.io/prp/jupyter-stack/tensorflow:v1.3
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
        cpu: 4
        memory: 4Gi
      requests:
        nvidia.com/gpu: 1
        cpu: 1
        memory: 2Gi